---

- name: Network Getting Started First Playbook
  hosts: vmx
  gather_facts: false
  tasks:

    - name: Backup JunOS config
      junos_config:
        backup: yes
      register: backup_junos_location
      when: ansible_network_os == 'junos'

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes

    - name: Copy backup files into /tmp/backups/ (junos)
      copy:
        src: "{{ backup_junos_location.backup_path }}"
        dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
      when: ansible_network_os == 'junos'
